/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param storeId 店舗ID
 * @param itemIds 商品IDのカンマ区切り文字列（例：\"1,2,3\"）
 * @param deposit 預かり金額
 */


data class CreateSaleRequest (

    /* 店舗ID */
    @Json(name = "storeId")
    val storeId: kotlin.Int,

    /* 商品IDのカンマ区切り文字列（例：\"1,2,3\"） */
    @Json(name = "itemIds")
    val itemIds: kotlin.String,

    /* 預かり金額 */
    @Json(name = "deposit")
    val deposit: kotlin.Int

) {


}

