/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 売上ID
 * @param amount 合計金額
 * @param quantity 商品数
 * @param deposit 預かり金額
 * @param change おつり
 * @param storeId 店舗ID
 */


data class CreateSale201Response (

    /* 売上ID */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* 合計金額 */
    @Json(name = "amount")
    val amount: kotlin.Int? = null,

    /* 商品数 */
    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,

    /* 預かり金額 */
    @Json(name = "deposit")
    val deposit: kotlin.Int? = null,

    /* おつり */
    @Json(name = "change")
    val change: kotlin.Int? = null,

    /* 店舗ID */
    @Json(name = "storeId")
    val storeId: kotlin.Int? = null

) {


}

