/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code エラーコード
 * @param message エラーメッセージ
 * @param timestamp エラー発生時刻
 * @param path リクエストパス
 * @param details 追加の詳細情報
 */


data class ErrorResponse (

    /* エラーコード */
    @Json(name = "code")
    val code: kotlin.String,

    /* エラーメッセージ */
    @Json(name = "message")
    val message: kotlin.String,

    /* エラー発生時刻 */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* リクエストパス */
    @Json(name = "path")
    val path: kotlin.String? = null,

    /* 追加の詳細情報 */
    @Json(name = "details")
    val details: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

