/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemId 商品ID
 * @param itemName 商品名
 * @param barcode バーコード
 * @param quantity 数量
 * @param unitPrice 単価（リバー）
 * @param subtotal 小計（リバー）
 */


data class SaleItemResponse (

    /* 商品ID */
    @Json(name = "itemId")
    val itemId: kotlin.Int,

    /* 商品名 */
    @Json(name = "itemName")
    val itemName: kotlin.String,

    /* バーコード */
    @Json(name = "barcode")
    val barcode: kotlin.String,

    /* 数量 */
    @Json(name = "quantity")
    val quantity: kotlin.Int,

    /* 単価（リバー） */
    @Json(name = "unitPrice")
    val unitPrice: kotlin.Int,

    /* 小計（リバー） */
    @Json(name = "subtotal")
    val subtotal: kotlin.Int

) {


}

