/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import info.nukoneko.kidspos.sdk.models.SaleItemResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 売上ID
 * @param storeId 店舗ID
 * @param storeName 店舗名
 * @param totalAmount 合計金額（リバー）
 * @param deposit 預り金（リバー）
 * @param change お釣り（リバー）
 * @param saleTime 売上時刻
 * @param items 売上商品リスト
 */


data class SaleResponse (

    /* 売上ID */
    @Json(name = "id")
    val id: kotlin.Int,

    /* 店舗ID */
    @Json(name = "storeId")
    val storeId: kotlin.Int,

    /* 店舗名 */
    @Json(name = "storeName")
    val storeName: kotlin.String,

    /* 合計金額（リバー） */
    @Json(name = "totalAmount")
    val totalAmount: kotlin.Int,

    /* 預り金（リバー） */
    @Json(name = "deposit")
    val deposit: kotlin.Int,

    /* お釣り（リバー） */
    @Json(name = "change")
    val change: kotlin.Int,

    /* 売上時刻 */
    @Json(name = "saleTime")
    val saleTime: java.time.OffsetDateTime,

    /* 売上商品リスト */
    @Json(name = "items")
    val items: kotlin.collections.List<SaleItemResponse>? = null

) {


}

