/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status サーバーの稼働状態
 * @param version アプリケーションバージョン（semver）
 * @param apiVersion API互換バージョン。クライアント側で対応バージョンと比較する
 */


data class StatusResponse (

    /* サーバーの稼働状態 */
    @Json(name = "status")
    val status: kotlin.String,

    /* アプリケーションバージョン（semver） */
    @Json(name = "version")
    val version: kotlin.String,

    /* API互換バージョン。クライアント側で対応バージョンと比較する */
    @Json(name = "apiVersion")
    val apiVersion: kotlin.Int

) {


}

