/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.apis.ItemsApi
import info.nukoneko.kidspos.sdk.models.CreateItemRequest
import info.nukoneko.kidspos.sdk.models.ItemResponse
import info.nukoneko.kidspos.sdk.models.PartialUpdateItemRequest

class ItemsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ItemsApi
        //val apiInstance = ItemsApi()

        // to test createItem
        should("test createItem") {
            // uncomment below to test createItem
            //val createItemRequest : CreateItemRequest =  // CreateItemRequest | 
            //val result : ItemResponse = apiInstance.createItem(createItemRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteItem
        should("test deleteItem") {
            // uncomment below to test deleteItem
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //apiInstance.deleteItem(id)
        }

        // to test generateBarcodePdf
        should("test generateBarcodePdf") {
            // uncomment below to test generateBarcodePdf
            //val result : java.io.File = apiInstance.generateBarcodePdf()
            //result shouldBe ("TODO")
        }

        // to test getAllItems
        should("test getAllItems") {
            // uncomment below to test getAllItems
            //val result : kotlin.collections.List<ItemResponse> = apiInstance.getAllItems()
            //result shouldBe ("TODO")
        }

        // to test getItemByBarcode
        should("test getItemByBarcode") {
            // uncomment below to test getItemByBarcode
            //val barcode : kotlin.String = barcode_example // kotlin.String | 
            //val result : ItemResponse = apiInstance.getItemByBarcode(barcode)
            //result shouldBe ("TODO")
        }

        // to test getItemById
        should("test getItemById") {
            // uncomment below to test getItemById
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val result : ItemResponse = apiInstance.getItemById(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdateItem
        should("test partialUpdateItem") {
            // uncomment below to test partialUpdateItem
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val partialUpdateItemRequest : PartialUpdateItemRequest =  // PartialUpdateItemRequest | 
            //val result : ItemResponse = apiInstance.partialUpdateItem(id, partialUpdateItemRequest)
            //result shouldBe ("TODO")
        }

        // to test updateItem
        should("test updateItem") {
            // uncomment below to test updateItem
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val createItemRequest : CreateItemRequest =  // CreateItemRequest | 
            //val result : ItemResponse = apiInstance.updateItem(id, createItemRequest)
            //result shouldBe ("TODO")
        }

    }
}
