/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.apis.SalesApi
import info.nukoneko.kidspos.sdk.models.CreateSale201Response
import info.nukoneko.kidspos.sdk.models.CreateSaleRequest
import info.nukoneko.kidspos.sdk.models.ErrorResponse
import info.nukoneko.kidspos.sdk.models.SaleResponse
import info.nukoneko.kidspos.sdk.models.ValidatePrinter200Response

class SalesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SalesApi
        //val apiInstance = SalesApi()

        // to test createSale
        should("test createSale") {
            // uncomment below to test createSale
            //val createSaleRequest : CreateSaleRequest =  // CreateSaleRequest | 
            //val result : CreateSale201Response = apiInstance.createSale(createSaleRequest)
            //result shouldBe ("TODO")
        }

        // to test getAllSales
        should("test getAllSales") {
            // uncomment below to test getAllSales
            //val result : kotlin.collections.List<SaleResponse> = apiInstance.getAllSales()
            //result shouldBe ("TODO")
        }

        // to test getSaleById
        should("test getSaleById") {
            // uncomment below to test getSaleById
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val result : SaleResponse = apiInstance.getSaleById(id)
            //result shouldBe ("TODO")
        }

        // to test validatePrinter
        should("test validatePrinter") {
            // uncomment below to test validatePrinter
            //val storeId : kotlin.Int = 56 // kotlin.Int | 
            //val result : ValidatePrinter200Response = apiInstance.validatePrinter(storeId)
            //result shouldBe ("TODO")
        }

    }
}
