/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.apis.SettingsApi
import info.nukoneko.kidspos.sdk.models.ApplicationSetting
import info.nukoneko.kidspos.sdk.models.GetPrinterSettings200Response
import info.nukoneko.kidspos.sdk.models.SaveApplicationSettings200Response
import info.nukoneko.kidspos.sdk.models.SavePrinterSettings200Response
import info.nukoneko.kidspos.sdk.models.SavePrinterSettingsRequest
import info.nukoneko.kidspos.sdk.models.SettingEntity
import info.nukoneko.kidspos.sdk.models.StatusResponse

class SettingsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsApi
        //val apiInstance = SettingsApi()

        // to test createSetting
        should("test createSetting") {
            // uncomment below to test createSetting
            //val settingEntity : SettingEntity =  // SettingEntity | 
            //val result : SettingEntity = apiInstance.createSetting(settingEntity)
            //result shouldBe ("TODO")
        }

        // to test deleteSetting
        should("test deleteSetting") {
            // uncomment below to test deleteSetting
            //val key : kotlin.String = key_example // kotlin.String | 
            //apiInstance.deleteSetting(key)
        }

        // to test getAllSettings
        should("test getAllSettings") {
            // uncomment below to test getAllSettings
            //val result : kotlin.collections.List<SettingEntity> = apiInstance.getAllSettings()
            //result shouldBe ("TODO")
        }

        // to test getApplicationSettings
        should("test getApplicationSettings") {
            // uncomment below to test getApplicationSettings
            //val result : ApplicationSetting = apiInstance.getApplicationSettings()
            //result shouldBe ("TODO")
        }

        // to test getPrinterSettings
        should("test getPrinterSettings") {
            // uncomment below to test getPrinterSettings
            //val storeId : kotlin.Int = 56 // kotlin.Int | 
            //val result : GetPrinterSettings200Response = apiInstance.getPrinterSettings(storeId)
            //result shouldBe ("TODO")
        }

        // to test getSettingByKey
        should("test getSettingByKey") {
            // uncomment below to test getSettingByKey
            //val key : kotlin.String = key_example // kotlin.String | 
            //val result : SettingEntity = apiInstance.getSettingByKey(key)
            //result shouldBe ("TODO")
        }

        // to test getStatus
        should("test getStatus") {
            // uncomment below to test getStatus
            //val result : StatusResponse = apiInstance.getStatus()
            //result shouldBe ("TODO")
        }

        // to test saveApplicationSettings
        should("test saveApplicationSettings") {
            // uncomment below to test saveApplicationSettings
            //val applicationSetting : ApplicationSetting =  // ApplicationSetting | 
            //val result : SaveApplicationSettings200Response = apiInstance.saveApplicationSettings(applicationSetting)
            //result shouldBe ("TODO")
        }

        // to test savePrinterSettings
        should("test savePrinterSettings") {
            // uncomment below to test savePrinterSettings
            //val storeId : kotlin.Int = 56 // kotlin.Int | 
            //val savePrinterSettingsRequest : SavePrinterSettingsRequest =  // SavePrinterSettingsRequest | 
            //val result : SavePrinterSettings200Response = apiInstance.savePrinterSettings(storeId, savePrinterSettingsRequest)
            //result shouldBe ("TODO")
        }

        // to test updateSetting
        should("test updateSetting") {
            // uncomment below to test updateSetting
            //val key : kotlin.String = key_example // kotlin.String | 
            //val `value` : kotlin.String = `value`_example // kotlin.String | 
            //val result : SettingEntity = apiInstance.updateSetting(key, `value`)
            //result shouldBe ("TODO")
        }

    }
}
