/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.apis.StatusApi
import info.nukoneko.kidspos.sdk.models.StatusResponse

class StatusApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatusApi
        //val apiInstance = StatusApi()

        // to test getServerStatus
        should("test getServerStatus") {
            // uncomment below to test getServerStatus
            //val result : StatusResponse = apiInstance.getServerStatus()
            //result shouldBe ("TODO")
        }

    }
}
