/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.apis.StoresApi
import info.nukoneko.kidspos.sdk.models.StoreEntity

class StoresApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StoresApi
        //val apiInstance = StoresApi()

        // to test createStore
        should("test createStore") {
            // uncomment below to test createStore
            //val storeEntity : StoreEntity =  // StoreEntity | 
            //val result : StoreEntity = apiInstance.createStore(storeEntity)
            //result shouldBe ("TODO")
        }

        // to test deleteStore
        should("test deleteStore") {
            // uncomment below to test deleteStore
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //apiInstance.deleteStore(id)
        }

        // to test getAllStores
        should("test getAllStores") {
            // uncomment below to test getAllStores
            //val result : kotlin.collections.List<StoreEntity> = apiInstance.getAllStores()
            //result shouldBe ("TODO")
        }

        // to test getStoreById
        should("test getStoreById") {
            // uncomment below to test getStoreById
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val result : StoreEntity = apiInstance.getStoreById(id)
            //result shouldBe ("TODO")
        }

        // to test updateStore
        should("test updateStore") {
            // uncomment below to test updateStore
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val storeEntity : StoreEntity =  // StoreEntity | 
            //val result : StoreEntity = apiInstance.updateStore(id, storeEntity)
            //result shouldBe ("TODO")
        }

    }
}
