/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.CreateSale201Response

class CreateSale201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateSale201Response
        //val modelInstance = CreateSale201Response()

        // to test the property `id` - 売上ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `amount` - 合計金額
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `quantity` - 商品数
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `deposit` - 預かり金額
        should("test deposit") {
            // uncomment below to test the property
            //modelInstance.deposit shouldBe ("TODO")
        }

        // to test the property `change` - おつり
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `storeId` - 店舗ID
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

    }
}
