/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.CreateSaleRequest

class CreateSaleRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateSaleRequest
        //val modelInstance = CreateSaleRequest()

        // to test the property `storeId` - 店舗ID
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

        // to test the property `itemIds` - 商品IDのカンマ区切り文字列（例：\"1,2,3\"）
        should("test itemIds") {
            // uncomment below to test the property
            //modelInstance.itemIds shouldBe ("TODO")
        }

        // to test the property `deposit` - 預かり金額
        should("test deposit") {
            // uncomment below to test the property
            //modelInstance.deposit shouldBe ("TODO")
        }

    }
}
