/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.ErrorResponse

class ErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorResponse
        //val modelInstance = ErrorResponse()

        // to test the property `code` - エラーコード
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message` - エラーメッセージ
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `timestamp` - エラー発生時刻
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `path` - リクエストパス
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `details` - 追加の詳細情報
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

    }
}
