/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.SaleItemResponse

class SaleItemResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SaleItemResponse
        //val modelInstance = SaleItemResponse()

        // to test the property `itemId` - 商品ID
        should("test itemId") {
            // uncomment below to test the property
            //modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `itemName` - 商品名
        should("test itemName") {
            // uncomment below to test the property
            //modelInstance.itemName shouldBe ("TODO")
        }

        // to test the property `barcode` - バーコード
        should("test barcode") {
            // uncomment below to test the property
            //modelInstance.barcode shouldBe ("TODO")
        }

        // to test the property `quantity` - 数量
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `unitPrice` - 単価（リバー）
        should("test unitPrice") {
            // uncomment below to test the property
            //modelInstance.unitPrice shouldBe ("TODO")
        }

        // to test the property `subtotal` - 小計（リバー）
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

    }
}
