/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.SaleResponse
import info.nukoneko.kidspos.sdk.models.SaleItemResponse

class SaleResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SaleResponse
        //val modelInstance = SaleResponse()

        // to test the property `id` - 売上ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `storeId` - 店舗ID
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

        // to test the property `storeName` - 店舗名
        should("test storeName") {
            // uncomment below to test the property
            //modelInstance.storeName shouldBe ("TODO")
        }

        // to test the property `totalAmount` - 合計金額（リバー）
        should("test totalAmount") {
            // uncomment below to test the property
            //modelInstance.totalAmount shouldBe ("TODO")
        }

        // to test the property `deposit` - 預り金（リバー）
        should("test deposit") {
            // uncomment below to test the property
            //modelInstance.deposit shouldBe ("TODO")
        }

        // to test the property `change` - お釣り（リバー）
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `saleTime` - 売上時刻
        should("test saleTime") {
            // uncomment below to test the property
            //modelInstance.saleTime shouldBe ("TODO")
        }

        // to test the property `items` - 売上商品リスト
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
