/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.SaveApplicationSettings200Response

class SaveApplicationSettings200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SaveApplicationSettings200Response
        //val modelInstance = SaveApplicationSettings200Response()

        // to test the property `serverHost`
        should("test serverHost") {
            // uncomment below to test the property
            //modelInstance.serverHost shouldBe ("TODO")
        }

        // to test the property `serverPort`
        should("test serverPort") {
            // uncomment below to test the property
            //modelInstance.serverPort shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
