/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.StatusResponse

class StatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatusResponse
        //val modelInstance = StatusResponse()

        // to test the property `status` - サーバーの稼働状態
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `version` - アプリケーションバージョン（semver）
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `apiVersion` - API互換バージョン。クライアント側で対応バージョンと比較する
        should("test apiVersion") {
            // uncomment below to test the property
            //modelInstance.apiVersion shouldBe ("TODO")
        }

    }
}
