/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import info.nukoneko.kidspos.sdk.models.ValidatePrinter200Response

class ValidatePrinter200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidatePrinter200Response
        //val modelInstance = ValidatePrinter200Response()

        // to test the property `isValid`
        should("test isValid") {
            // uncomment below to test the property
            //modelInstance.isValid shouldBe ("TODO")
        }

    }
}
