/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import info.nukoneko.kidspos.sdk.models.CreateItemRequest
import info.nukoneko.kidspos.sdk.models.ItemResponse
import info.nukoneko.kidspos.sdk.models.PartialUpdateItemRequest

import com.squareup.moshi.Json

import info.nukoneko.kidspos.sdk.infrastructure.ApiClient
import info.nukoneko.kidspos.sdk.infrastructure.ApiResponse
import info.nukoneko.kidspos.sdk.infrastructure.ClientException
import info.nukoneko.kidspos.sdk.infrastructure.ClientError
import info.nukoneko.kidspos.sdk.infrastructure.ServerException
import info.nukoneko.kidspos.sdk.infrastructure.ServerError
import info.nukoneko.kidspos.sdk.infrastructure.MultiValueMap
import info.nukoneko.kidspos.sdk.infrastructure.PartConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestMethod
import info.nukoneko.kidspos.sdk.infrastructure.ResponseType
import info.nukoneko.kidspos.sdk.infrastructure.Success
import info.nukoneko.kidspos.sdk.infrastructure.toMultiValue

open class ItemsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost:8080")
        }
    }

    /**
     * POST /api/item
     * 商品登録
     * 新しい商品を登録します
     * @param createItemRequest 
     * @return ItemResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createItem(createItemRequest: CreateItemRequest) : ItemResponse {
        val localVarResponse = createItemWithHttpInfo(createItemRequest = createItemRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/item
     * 商品登録
     * 新しい商品を登録します
     * @param createItemRequest 
     * @return ApiResponse<ItemResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createItemWithHttpInfo(createItemRequest: CreateItemRequest) : ApiResponse<ItemResponse?> {
        val localVariableConfig = createItemRequestConfig(createItemRequest = createItemRequest)

        return request<CreateItemRequest, ItemResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createItem
     *
     * @param createItemRequest 
     * @return RequestConfig
     */
    fun createItemRequestConfig(createItemRequest: CreateItemRequest) : RequestConfig<CreateItemRequest> {
        val localVariableBody = createItemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/item",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/item/{id}
     * 商品削除
     * 指定したIDの商品を削除します
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteItem(id: kotlin.Int) : Unit {
        val localVarResponse = deleteItemWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/item/{id}
     * 商品削除
     * 指定したIDの商品を削除します
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteItemWithHttpInfo(id: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deleteItemRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteItem
     *
     * @param id 
     * @return RequestConfig
     */
    fun deleteItemRequestConfig(id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/item/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/item/barcode-pdf
     * バーコードPDF生成
     * 全商品のバーコードをPDF形式で生成します
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun generateBarcodePdf() : java.io.File {
        val localVarResponse = generateBarcodePdfWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/item/barcode-pdf
     * バーコードPDF生成
     * 全商品のバーコードをPDF形式で生成します
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun generateBarcodePdfWithHttpInfo() : ApiResponse<java.io.File?> {
        val localVariableConfig = generateBarcodePdfRequestConfig()

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation generateBarcodePdf
     *
     * @return RequestConfig
     */
    fun generateBarcodePdfRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/item/barcode-pdf",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/item
     * 商品一覧取得
     * 登録されている全商品を取得します
     * @return kotlin.collections.List<ItemResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAllItems() : kotlin.collections.List<ItemResponse> {
        val localVarResponse = getAllItemsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ItemResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/item
     * 商品一覧取得
     * 登録されている全商品を取得します
     * @return ApiResponse<kotlin.collections.List<ItemResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getAllItemsWithHttpInfo() : ApiResponse<kotlin.collections.List<ItemResponse>?> {
        val localVariableConfig = getAllItemsRequestConfig()

        return request<Unit, kotlin.collections.List<ItemResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllItems
     *
     * @return RequestConfig
     */
    fun getAllItemsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/item",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/item/barcode/{barcode}
     * バーコードで商品取得
     * バーコードから商品を検索します
     * @param barcode 
     * @return ItemResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getItemByBarcode(barcode: kotlin.String) : ItemResponse {
        val localVarResponse = getItemByBarcodeWithHttpInfo(barcode = barcode)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/item/barcode/{barcode}
     * バーコードで商品取得
     * バーコードから商品を検索します
     * @param barcode 
     * @return ApiResponse<ItemResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getItemByBarcodeWithHttpInfo(barcode: kotlin.String) : ApiResponse<ItemResponse?> {
        val localVariableConfig = getItemByBarcodeRequestConfig(barcode = barcode)

        return request<Unit, ItemResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getItemByBarcode
     *
     * @param barcode 
     * @return RequestConfig
     */
    fun getItemByBarcodeRequestConfig(barcode: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/item/barcode/{barcode}".replace("{"+"barcode"+"}", encodeURIComponent(barcode.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/item/{id}
     * 商品取得
     * 指定したIDの商品を取得します
     * @param id 
     * @return ItemResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getItemById(id: kotlin.Int) : ItemResponse {
        val localVarResponse = getItemByIdWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/item/{id}
     * 商品取得
     * 指定したIDの商品を取得します
     * @param id 
     * @return ApiResponse<ItemResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getItemByIdWithHttpInfo(id: kotlin.Int) : ApiResponse<ItemResponse?> {
        val localVariableConfig = getItemByIdRequestConfig(id = id)

        return request<Unit, ItemResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getItemById
     *
     * @param id 
     * @return RequestConfig
     */
    fun getItemByIdRequestConfig(id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/item/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/item/{id}
     * 商品部分更新
     * 指定したIDの商品を部分的に更新します
     * @param id 
     * @param partialUpdateItemRequest 
     * @return ItemResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun partialUpdateItem(id: kotlin.Int, partialUpdateItemRequest: PartialUpdateItemRequest) : ItemResponse {
        val localVarResponse = partialUpdateItemWithHttpInfo(id = id, partialUpdateItemRequest = partialUpdateItemRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/item/{id}
     * 商品部分更新
     * 指定したIDの商品を部分的に更新します
     * @param id 
     * @param partialUpdateItemRequest 
     * @return ApiResponse<ItemResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun partialUpdateItemWithHttpInfo(id: kotlin.Int, partialUpdateItemRequest: PartialUpdateItemRequest) : ApiResponse<ItemResponse?> {
        val localVariableConfig = partialUpdateItemRequestConfig(id = id, partialUpdateItemRequest = partialUpdateItemRequest)

        return request<PartialUpdateItemRequest, ItemResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation partialUpdateItem
     *
     * @param id 
     * @param partialUpdateItemRequest 
     * @return RequestConfig
     */
    fun partialUpdateItemRequestConfig(id: kotlin.Int, partialUpdateItemRequest: PartialUpdateItemRequest) : RequestConfig<PartialUpdateItemRequest> {
        val localVariableBody = partialUpdateItemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/item/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/item/{id}
     * 商品更新
     * 指定したIDの商品を更新します
     * @param id 
     * @param createItemRequest 
     * @return ItemResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateItem(id: kotlin.Int, createItemRequest: CreateItemRequest) : ItemResponse {
        val localVarResponse = updateItemWithHttpInfo(id = id, createItemRequest = createItemRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/item/{id}
     * 商品更新
     * 指定したIDの商品を更新します
     * @param id 
     * @param createItemRequest 
     * @return ApiResponse<ItemResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateItemWithHttpInfo(id: kotlin.Int, createItemRequest: CreateItemRequest) : ApiResponse<ItemResponse?> {
        val localVariableConfig = updateItemRequestConfig(id = id, createItemRequest = createItemRequest)

        return request<CreateItemRequest, ItemResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateItem
     *
     * @param id 
     * @param createItemRequest 
     * @return RequestConfig
     */
    fun updateItemRequestConfig(id: kotlin.Int, createItemRequest: CreateItemRequest) : RequestConfig<CreateItemRequest> {
        val localVariableBody = createItemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/item/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
