/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import info.nukoneko.kidspos.sdk.models.CreateSale201Response
import info.nukoneko.kidspos.sdk.models.CreateSaleRequest
import info.nukoneko.kidspos.sdk.models.ErrorResponse
import info.nukoneko.kidspos.sdk.models.SaleResponse
import info.nukoneko.kidspos.sdk.models.ValidatePrinter200Response

import com.squareup.moshi.Json

import info.nukoneko.kidspos.sdk.infrastructure.ApiClient
import info.nukoneko.kidspos.sdk.infrastructure.ApiResponse
import info.nukoneko.kidspos.sdk.infrastructure.ClientException
import info.nukoneko.kidspos.sdk.infrastructure.ClientError
import info.nukoneko.kidspos.sdk.infrastructure.ServerException
import info.nukoneko.kidspos.sdk.infrastructure.ServerError
import info.nukoneko.kidspos.sdk.infrastructure.MultiValueMap
import info.nukoneko.kidspos.sdk.infrastructure.PartConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestMethod
import info.nukoneko.kidspos.sdk.infrastructure.ResponseType
import info.nukoneko.kidspos.sdk.infrastructure.Success
import info.nukoneko.kidspos.sdk.infrastructure.toMultiValue

open class SalesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost:8080")
        }
    }

    /**
     * POST /api/sales
     * 売上登録
     * 新しい売上を登録します
     * @param createSaleRequest 
     * @return CreateSale201Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createSale(createSaleRequest: CreateSaleRequest) : CreateSale201Response {
        val localVarResponse = createSaleWithHttpInfo(createSaleRequest = createSaleRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateSale201Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/sales
     * 売上登録
     * 新しい売上を登録します
     * @param createSaleRequest 
     * @return ApiResponse<CreateSale201Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createSaleWithHttpInfo(createSaleRequest: CreateSaleRequest) : ApiResponse<CreateSale201Response?> {
        val localVariableConfig = createSaleRequestConfig(createSaleRequest = createSaleRequest)

        return request<CreateSaleRequest, CreateSale201Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createSale
     *
     * @param createSaleRequest 
     * @return RequestConfig
     */
    fun createSaleRequestConfig(createSaleRequest: CreateSaleRequest) : RequestConfig<CreateSaleRequest> {
        val localVariableBody = createSaleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/sales",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/sales
     * 売上一覧取得
     * 全売上データを取得します
     * @return kotlin.collections.List<SaleResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAllSales() : kotlin.collections.List<SaleResponse> {
        val localVarResponse = getAllSalesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SaleResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/sales
     * 売上一覧取得
     * 全売上データを取得します
     * @return ApiResponse<kotlin.collections.List<SaleResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getAllSalesWithHttpInfo() : ApiResponse<kotlin.collections.List<SaleResponse>?> {
        val localVariableConfig = getAllSalesRequestConfig()

        return request<Unit, kotlin.collections.List<SaleResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllSales
     *
     * @return RequestConfig
     */
    fun getAllSalesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/sales",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/sales/{id}
     * 売上詳細取得
     * 指定したIDの売上詳細を取得します
     * @param id 
     * @return SaleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSaleById(id: kotlin.Int) : SaleResponse {
        val localVarResponse = getSaleByIdWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SaleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/sales/{id}
     * 売上詳細取得
     * 指定したIDの売上詳細を取得します
     * @param id 
     * @return ApiResponse<SaleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getSaleByIdWithHttpInfo(id: kotlin.Int) : ApiResponse<SaleResponse?> {
        val localVariableConfig = getSaleByIdRequestConfig(id = id)

        return request<Unit, SaleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getSaleById
     *
     * @param id 
     * @return RequestConfig
     */
    fun getSaleByIdRequestConfig(id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/sales/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/sales/validate-printer/{storeId}
     * プリンター設定確認
     * 指定した店舗のプリンター設定を確認します
     * @param storeId 
     * @return ValidatePrinter200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun validatePrinter(storeId: kotlin.Int) : ValidatePrinter200Response {
        val localVarResponse = validatePrinterWithHttpInfo(storeId = storeId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ValidatePrinter200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/sales/validate-printer/{storeId}
     * プリンター設定確認
     * 指定した店舗のプリンター設定を確認します
     * @param storeId 
     * @return ApiResponse<ValidatePrinter200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun validatePrinterWithHttpInfo(storeId: kotlin.Int) : ApiResponse<ValidatePrinter200Response?> {
        val localVariableConfig = validatePrinterRequestConfig(storeId = storeId)

        return request<Unit, ValidatePrinter200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation validatePrinter
     *
     * @param storeId 
     * @return RequestConfig
     */
    fun validatePrinterRequestConfig(storeId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/sales/validate-printer/{storeId}".replace("{"+"storeId"+"}", encodeURIComponent(storeId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
