/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import info.nukoneko.kidspos.sdk.models.ApplicationSetting
import info.nukoneko.kidspos.sdk.models.GetPrinterSettings200Response
import info.nukoneko.kidspos.sdk.models.SaveApplicationSettings200Response
import info.nukoneko.kidspos.sdk.models.SavePrinterSettings200Response
import info.nukoneko.kidspos.sdk.models.SavePrinterSettingsRequest
import info.nukoneko.kidspos.sdk.models.SettingEntity
import info.nukoneko.kidspos.sdk.models.StatusResponse

import com.squareup.moshi.Json

import info.nukoneko.kidspos.sdk.infrastructure.ApiClient
import info.nukoneko.kidspos.sdk.infrastructure.ApiResponse
import info.nukoneko.kidspos.sdk.infrastructure.ClientException
import info.nukoneko.kidspos.sdk.infrastructure.ClientError
import info.nukoneko.kidspos.sdk.infrastructure.ServerException
import info.nukoneko.kidspos.sdk.infrastructure.ServerError
import info.nukoneko.kidspos.sdk.infrastructure.MultiValueMap
import info.nukoneko.kidspos.sdk.infrastructure.PartConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestMethod
import info.nukoneko.kidspos.sdk.infrastructure.ResponseType
import info.nukoneko.kidspos.sdk.infrastructure.Success
import info.nukoneko.kidspos.sdk.infrastructure.toMultiValue

open class SettingsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost:8080")
        }
    }

    /**
     * POST /api/setting
     * 設定作成
     * 新しい設定を作成します
     * @param settingEntity 
     * @return SettingEntity
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createSetting(settingEntity: SettingEntity) : SettingEntity {
        val localVarResponse = createSettingWithHttpInfo(settingEntity = settingEntity)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SettingEntity
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/setting
     * 設定作成
     * 新しい設定を作成します
     * @param settingEntity 
     * @return ApiResponse<SettingEntity?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createSettingWithHttpInfo(settingEntity: SettingEntity) : ApiResponse<SettingEntity?> {
        val localVariableConfig = createSettingRequestConfig(settingEntity = settingEntity)

        return request<SettingEntity, SettingEntity>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createSetting
     *
     * @param settingEntity 
     * @return RequestConfig
     */
    fun createSettingRequestConfig(settingEntity: SettingEntity) : RequestConfig<SettingEntity> {
        val localVariableBody = settingEntity
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/setting",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/setting/{key}
     * 設定削除
     * 設定を削除します
     * @param key 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteSetting(key: kotlin.String) : Unit {
        val localVarResponse = deleteSettingWithHttpInfo(key = key)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/setting/{key}
     * 設定削除
     * 設定を削除します
     * @param key 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteSettingWithHttpInfo(key: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = deleteSettingRequestConfig(key = key)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteSetting
     *
     * @param key 
     * @return RequestConfig
     */
    fun deleteSettingRequestConfig(key: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/setting/{key}".replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/setting
     * 設定一覧取得
     * 全設定を取得します
     * @return kotlin.collections.List<SettingEntity>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAllSettings() : kotlin.collections.List<SettingEntity> {
        val localVarResponse = getAllSettingsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SettingEntity>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/setting
     * 設定一覧取得
     * 全設定を取得します
     * @return ApiResponse<kotlin.collections.List<SettingEntity>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getAllSettingsWithHttpInfo() : ApiResponse<kotlin.collections.List<SettingEntity>?> {
        val localVariableConfig = getAllSettingsRequestConfig()

        return request<Unit, kotlin.collections.List<SettingEntity>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllSettings
     *
     * @return RequestConfig
     */
    fun getAllSettingsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/setting",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/setting/application
     * アプリケーション設定取得
     * アプリケーション全体の設定を取得します
     * @return ApplicationSetting
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getApplicationSettings() : ApplicationSetting {
        val localVarResponse = getApplicationSettingsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApplicationSetting
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/setting/application
     * アプリケーション設定取得
     * アプリケーション全体の設定を取得します
     * @return ApiResponse<ApplicationSetting?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getApplicationSettingsWithHttpInfo() : ApiResponse<ApplicationSetting?> {
        val localVariableConfig = getApplicationSettingsRequestConfig()

        return request<Unit, ApplicationSetting>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getApplicationSettings
     *
     * @return RequestConfig
     */
    fun getApplicationSettingsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/setting/application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/setting/printer/{storeId}
     * プリンター設定取得
     * 店舗のプリンター設定を取得します
     * @param storeId 
     * @return GetPrinterSettings200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getPrinterSettings(storeId: kotlin.Int) : GetPrinterSettings200Response {
        val localVarResponse = getPrinterSettingsWithHttpInfo(storeId = storeId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetPrinterSettings200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/setting/printer/{storeId}
     * プリンター設定取得
     * 店舗のプリンター設定を取得します
     * @param storeId 
     * @return ApiResponse<GetPrinterSettings200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getPrinterSettingsWithHttpInfo(storeId: kotlin.Int) : ApiResponse<GetPrinterSettings200Response?> {
        val localVariableConfig = getPrinterSettingsRequestConfig(storeId = storeId)

        return request<Unit, GetPrinterSettings200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getPrinterSettings
     *
     * @param storeId 
     * @return RequestConfig
     */
    fun getPrinterSettingsRequestConfig(storeId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/setting/printer/{storeId}".replace("{"+"storeId"+"}", encodeURIComponent(storeId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/setting/{key}
     * 設定取得
     * 指定したキーの設定を取得します
     * @param key 
     * @return SettingEntity
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSettingByKey(key: kotlin.String) : SettingEntity {
        val localVarResponse = getSettingByKeyWithHttpInfo(key = key)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SettingEntity
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/setting/{key}
     * 設定取得
     * 指定したキーの設定を取得します
     * @param key 
     * @return ApiResponse<SettingEntity?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getSettingByKeyWithHttpInfo(key: kotlin.String) : ApiResponse<SettingEntity?> {
        val localVariableConfig = getSettingByKeyRequestConfig(key = key)

        return request<Unit, SettingEntity>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getSettingByKey
     *
     * @param key 
     * @return RequestConfig
     */
    fun getSettingByKeyRequestConfig(key: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/setting/{key}".replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/setting/status
     * ステータス取得
     * APIのステータスを取得します。後方互換のため維持しています。/api/status を使用してください
     * @return StatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun getStatus() : StatusResponse {
        @Suppress("DEPRECATION")
        val localVarResponse = getStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/setting/status
     * ステータス取得
     * APIのステータスを取得します。後方互換のため維持しています。/api/status を使用してください
     * @return ApiResponse<StatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun getStatusWithHttpInfo() : ApiResponse<StatusResponse?> {
        @Suppress("DEPRECATION")
        val localVariableConfig = getStatusRequestConfig()

        return request<Unit, StatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getStatus
     *
     * @return RequestConfig
     */
    @Deprecated(message = "This operation is deprecated.")
    fun getStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/setting/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/setting/application
     * アプリケーション設定保存
     * アプリケーション全体の設定を保存します
     * @param applicationSetting 
     * @return SaveApplicationSettings200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun saveApplicationSettings(applicationSetting: ApplicationSetting) : SaveApplicationSettings200Response {
        val localVarResponse = saveApplicationSettingsWithHttpInfo(applicationSetting = applicationSetting)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SaveApplicationSettings200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/setting/application
     * アプリケーション設定保存
     * アプリケーション全体の設定を保存します
     * @param applicationSetting 
     * @return ApiResponse<SaveApplicationSettings200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun saveApplicationSettingsWithHttpInfo(applicationSetting: ApplicationSetting) : ApiResponse<SaveApplicationSettings200Response?> {
        val localVariableConfig = saveApplicationSettingsRequestConfig(applicationSetting = applicationSetting)

        return request<ApplicationSetting, SaveApplicationSettings200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation saveApplicationSettings
     *
     * @param applicationSetting 
     * @return RequestConfig
     */
    fun saveApplicationSettingsRequestConfig(applicationSetting: ApplicationSetting) : RequestConfig<ApplicationSetting> {
        val localVariableBody = applicationSetting
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/setting/application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/setting/printer/{storeId}
     * プリンター設定保存
     * 店舗のプリンター設定を保存します
     * @param storeId 
     * @param savePrinterSettingsRequest 
     * @return SavePrinterSettings200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun savePrinterSettings(storeId: kotlin.Int, savePrinterSettingsRequest: SavePrinterSettingsRequest) : SavePrinterSettings200Response {
        val localVarResponse = savePrinterSettingsWithHttpInfo(storeId = storeId, savePrinterSettingsRequest = savePrinterSettingsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SavePrinterSettings200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/setting/printer/{storeId}
     * プリンター設定保存
     * 店舗のプリンター設定を保存します
     * @param storeId 
     * @param savePrinterSettingsRequest 
     * @return ApiResponse<SavePrinterSettings200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun savePrinterSettingsWithHttpInfo(storeId: kotlin.Int, savePrinterSettingsRequest: SavePrinterSettingsRequest) : ApiResponse<SavePrinterSettings200Response?> {
        val localVariableConfig = savePrinterSettingsRequestConfig(storeId = storeId, savePrinterSettingsRequest = savePrinterSettingsRequest)

        return request<SavePrinterSettingsRequest, SavePrinterSettings200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation savePrinterSettings
     *
     * @param storeId 
     * @param savePrinterSettingsRequest 
     * @return RequestConfig
     */
    fun savePrinterSettingsRequestConfig(storeId: kotlin.Int, savePrinterSettingsRequest: SavePrinterSettingsRequest) : RequestConfig<SavePrinterSettingsRequest> {
        val localVariableBody = savePrinterSettingsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/setting/printer/{storeId}".replace("{"+"storeId"+"}", encodeURIComponent(storeId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/setting/{key}
     * 設定更新
     * 設定を更新します
     * @param key 
     * @param `value` 
     * @return SettingEntity
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateSetting(key: kotlin.String, `value`: kotlin.String) : SettingEntity {
        val localVarResponse = updateSettingWithHttpInfo(key = key, `value` = `value`)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SettingEntity
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/setting/{key}
     * 設定更新
     * 設定を更新します
     * @param key 
     * @param `value` 
     * @return ApiResponse<SettingEntity?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateSettingWithHttpInfo(key: kotlin.String, `value`: kotlin.String) : ApiResponse<SettingEntity?> {
        val localVariableConfig = updateSettingRequestConfig(key = key, `value` = `value`)

        return request<Map<String, PartConfig<*>>, SettingEntity>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateSetting
     *
     * @param key 
     * @param `value` 
     * @return RequestConfig
     */
    fun updateSettingRequestConfig(key: kotlin.String, `value`: kotlin.String) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "value" to PartConfig(body = `value`, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "application/x-www-form-urlencoded")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/setting/{key}".replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
