/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package info.nukoneko.kidspos.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import info.nukoneko.kidspos.sdk.models.StatusResponse

import com.squareup.moshi.Json

import info.nukoneko.kidspos.sdk.infrastructure.ApiClient
import info.nukoneko.kidspos.sdk.infrastructure.ApiResponse
import info.nukoneko.kidspos.sdk.infrastructure.ClientException
import info.nukoneko.kidspos.sdk.infrastructure.ClientError
import info.nukoneko.kidspos.sdk.infrastructure.ServerException
import info.nukoneko.kidspos.sdk.infrastructure.ServerError
import info.nukoneko.kidspos.sdk.infrastructure.MultiValueMap
import info.nukoneko.kidspos.sdk.infrastructure.PartConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestConfig
import info.nukoneko.kidspos.sdk.infrastructure.RequestMethod
import info.nukoneko.kidspos.sdk.infrastructure.ResponseType
import info.nukoneko.kidspos.sdk.infrastructure.Success
import info.nukoneko.kidspos.sdk.infrastructure.toMultiValue

open class StatusApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost:8080")
        }
    }

    /**
     * GET /api/status
     * サーバーステータス取得
     * サーバーの稼働状態、アプリケーションバージョン、API互換バージョンを取得します。クライアントは apiVersion を自身の対応バージョンと比較し、不一致の場合はアップデートを促してください
     * @return StatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getServerStatus() : StatusResponse {
        val localVarResponse = getServerStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/status
     * サーバーステータス取得
     * サーバーの稼働状態、アプリケーションバージョン、API互換バージョンを取得します。クライアントは apiVersion を自身の対応バージョンと比較し、不一致の場合はアップデートを促してください
     * @return ApiResponse<StatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getServerStatusWithHttpInfo() : ApiResponse<StatusResponse?> {
        val localVariableConfig = getServerStatusRequestConfig()

        return request<Unit, StatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getServerStatus
     *
     * @return RequestConfig
     */
    fun getServerStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
